### ISSUE TITLE
Cannot compile with Qt 5.5

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2757]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 2870
Originally created at: Wed Apr 29 20:52:16 2015
Originally last updated at: Wed Apr 29 20:52:16 2015

Hello,

I can''t compile SQLite Studio with Qt 5.5. I got this error:

../../../coreSQLiteStudio/common/utils.cpp: In function &acirc;QByteArray hashToBytes(const QHash&lt;QString, QVariant&gt;&amp;)&acirc;:
../../../coreSQLiteStudio/common/utils.cpp:321:23: error: variable &acirc;QDataStream stream&acirc; has initializer but incomplete type
     QDataStream stream(&amp;bytes, QIODevice::WriteOnly);
                       ^
../../../coreSQLiteStudio/common/utils.cpp: In function &acirc;QHash&lt;QString, QVariant&gt; bytesToHash(const QByteArray&amp;)&acirc;:
../../../coreSQLiteStudio/common/utils.cpp:332:29: error: variable &acirc;QDataStream stream&acirc; has initializer but incomplete type
     QDataStream stream(bytes);
                             ^

\n\n**Operating system:**\nLinux 64-bit\n\n**Version:**\n3.0.5

**Comment by pawelsalawa** [comment]
Originally created at: Wed Apr 29 20:52:16 2015

I will wait for Qt 5.5 release. No point in fixing this before it's even released.

**Comment by pawelsalawa** [comment]
Originally created at: Wed Apr 29 20:52:16 2015

Okay, I understand.

Thank you.

**Comment by pawelsalawa** [comment]
Originally created at: Wed Apr 29 20:52:16 2015

_Status changed to **rejected**_

**Rejection reason:**
Not relevant, yet.

**Comment by pawelsalawa** [comment]
Originally created at: Wed Apr 29 20:52:16 2015

I was able to compile with Qt5.5 by including &lt;QDataStream&gt; in the following files. It appears that the include for this library was implied in previous versions of Qt.

SQLiteStudio3/coreSQLiteStudio/common/utils.cpp
SQLiteStudio3/coreSQLiteStudio/db/db.cpp
SQLiteStudio3/sqlitestudiocli/cli\\_config.cpp
